import type {
  LlmPromptTemplate,
  LlmStepConfig,
  LlmStepKey,
  LlmStepSettings,
} from "./types";

/** Bedrock on-demand often requires system inference profile IDs (`global.*`), not bare `anthropic.*` model IDs. */
export const defaultStepConfigs: Record<LlmStepKey, LlmStepConfig> = {
  "job-plan": {
    stepKey: "job-plan",
    provider: "bedrock",
    model: "global.anthropic.claude-sonnet-4-6",
    temperature: 0.7,
    maxOutputTokens: 700,
    secretIdEnvVar: "BEDROCK_LLM_SECRET_ID",
  },
  "scene-json": {
    stepKey: "scene-json",
    provider: "bedrock",
    model: "global.anthropic.claude-sonnet-4-6",
    temperature: 0.5,
    maxOutputTokens: 2400,
    secretIdEnvVar: "BEDROCK_LLM_SECRET_ID",
  },
  metadata: {
    stepKey: "metadata",
    provider: "bedrock",
    model: "global.anthropic.claude-haiku-4-5-20251001-v1:0",
    temperature: 0.3,
    maxOutputTokens: 700,
    secretIdEnvVar: "BEDROCK_LLM_SECRET_ID",
  },
  "youtube-publish-metadata": {
    stepKey: "youtube-publish-metadata",
    provider: "bedrock",
    model: "global.anthropic.claude-haiku-4-5-20251001-v1:0",
    temperature: 0.3,
    maxOutputTokens: 1200,
    secretIdEnvVar: "BEDROCK_LLM_SECRET_ID",
  },
};

export const defaultPromptTemplates: Record<LlmStepKey, LlmPromptTemplate> = {
  "job-plan": {
    stepKey: "job-plan",
    version: "v1-file-registry",
    systemPrompt: [
      "You are a short-form video planning assistant for an AI video pipeline.",
      "",
      "Your job is to propose one strong video plan that fits the given channel context and can be executed clearly as a 30 to 60 second short-form video.",
      "",
      "You must follow these rules:",
      "- Return valid JSON only.",
      "- Do not include markdown, code fences, commentary, or explanations.",
      "- Be specific, concrete, and production-minded.",
      "- Avoid sensational, misleading, or generic clickbait.",
      "- Match the requested target language.",
      "- Prefer ideas that can naturally be expressed in 4 to 7 scenes.",
      "- The plan should be suitable for a vertical 9:16 short-form format.",
      "",
      "The JSON schema must be:",
      "{",
      '  "titleIdea": string,',
      '  "targetDurationSec": number,',
      '  "stylePreset": string',
      "}",
    ].join("\n"),
    userPrompt: [
      "Create a short-form video plan for the following channel context.",
      "",
      'Return JSON with keys: "titleIdea", "targetDurationSec", "stylePreset".',
      "Constraints:",
      "- titleIdea must be specific and clickable without being sensational.",
      "- titleIdea should imply a clear viewer payoff, curiosity gap, or practical takeaway.",
      "- Avoid generic titles that could fit any channel.",
      "- targetDurationSec must be an integer between 30 and 60.",
      "- stylePreset must be a concise snake_case label describing tone + visual style.",
      "- The plan should fit a short-form video that can be executed in 4 to 7 scenes.",
      "- Match the output to targetLanguage.",
      "- The concept should be suitable for a vertical 9:16 short-form video.",
      "- If presetFormat, styleTags, voiceMode, subtitleMode, layoutMode, or assetStrategy are provided, treat them as hard creative constraints.",
      "",
      "Inputs:",
      "- contentId: {{contentId}}",
      "- targetLanguage: {{targetLanguage}}",
      "- channelLabel: {{channelLabel}}",
      "- contentType: {{contentType}}",
      "- variant: {{variant}}",
      "- presetId: {{presetId}}",
      "- presetFormat: {{presetFormat}}",
      "- styleTags: {{styleTags}}",
      "- voiceMode: {{voiceMode}}",
      "- subtitleMode: {{subtitleMode}}",
      "- layoutMode: {{layoutMode}}",
      "- assetStrategy: {{assetStrategy}}",
      "- creativeBrief: {{creativeBrief}}",
      "",
      "Output rules:",
      "- Do not include markdown.",
      "- Do not include explanation.",
      "- Output JSON only.",
    ].join("\n"),
  },
  "scene-json": {
    stepKey: "scene-json",
    version: "v1-file-registry",
    systemPrompt: [
      "You are a short-form video scene writer for an AI video pipeline.",
      "",
      "Your job is to turn a video idea into a clear, paced, visually strong scene JSON document suitable for image, video, voice, subtitle, and final render generation.",
      "",
      "You must follow these rules:",
      "- Return valid JSON only.",
      "- Do not include markdown, code fences, commentary, or explanations.",
      "- Scenes must feel like a coherent short-form video, not a loose list of facts.",
      "- After optional sceneId 0 (title slate), the next scene must open with a strong hook; if there is no scene 0, sceneId 1 must open with a strong hook.",
      "- Middle scenes must progress the idea without repetition.",
      "- The final scene must deliver a payoff, conclusion, or soft CTA.",
      "- Match all viewer-facing text to the requested target language.",
      "- Visual prompts must be concrete and production-ready.",
      "- Every visual must be composed for a vertical 9:16 short-form frame.",
      "",
      "The JSON schema must be:",
      "{",
      '  "videoTitle": string,',
      '  "language": string,',
      '  "scenes": [',
      "    {",
      '      "sceneId": number,',
      '      "durationSec": number,',
      '      "narration": string,',
      '      "imagePrompt": string,',
      '      "subtitle": string,',
      '      "videoPrompt": string | optional,',
      '      "bgmMood": string | optional,',
      '      "sfx": string[] | optional',
      "    }",
      "  ]",
      "}",
    ].join("\n"),
    userPrompt: [
      "Create a scene JSON document for a short-form AI video pipeline.",
      "",
      'Return JSON with keys: "videoTitle", "language", "scenes".',
      "",
      "Each scene must include:",
      '- "sceneId"',
      '- "durationSec"',
      '- "narration"',
      '- "imagePrompt"',
      '- "subtitle"',
      "",
      "Each scene may include:",
      '- "videoPrompt"',
      '- "bgmMood"',
      '- "sfx"',
      "",
      "Narrative goals:",
      "- After optional sceneId 0 (title slate), the next scene must open with a strong hook; if there is no scene 0, sceneId 1 must open with a strong hook.",
      "- Middle scenes must progress the idea with no repeated point or repeated visual concept.",
      "- Final scene must deliver a payoff, takeaway, or soft CTA.",
      "",
      "Constraints:",
      "- sceneId must be unique; use 0 only for an optional title-card or text-slate scene (keep narration minimal or empty); otherwise use 1, 2, 3… in order with no gaps.",
      "- Create 4 to 7 scenes unless the topic strongly requires otherwise.",
      "- Total duration across all scenes should be as close as possible to targetDurationSec, ideally within +/- 3 seconds.",
      "- durationSec should usually be between 6 and 10 seconds.",
      "- narration must sound natural for spoken short-form video.",
      "- subtitle must exactly match narration for each scene.",
      "- Do not shorten, summarize, paraphrase, or rewrite subtitle separately from narration.",
      "- imagePrompt and videoPrompt must be visually specific and production-ready.",
      "- Each visual prompt should mention subject, setting, framing, lighting, mood, and important motion if relevant.",
      "- Every visual prompt must explicitly target a vertical 9:16 short-form composition.",
      "- Favor portrait-safe composition, centered or vertically framed subjects, and enough headroom for mobile UI crop.",
      "- Avoid repeating the same setting, camera angle, or composition across consecutive scenes unless necessary.",
      '- Avoid vague phrases like "cinematic scene" without concrete details.',
      "- Keep prompts safe for generation and avoid branded or copyrighted characters.",
      "- Respect presetFormat, styleTags, voiceMode, subtitleMode, layoutMode, and assetStrategy when they are provided.",
      "- If voiceMode is disabled, keep narration empty or minimal and prefer visual storytelling.",
      "- If subtitleMode is minimal or disabled, avoid verbose on-screen text.",
      "- If layoutMode is template or still-motion, bias prompts and pacing toward that composition style.",
      "",
      "Inputs:",
      "- titleIdea: {{titleIdea}}",
      "- targetLanguage: {{targetLanguage}}",
      "- targetDurationSec: {{targetDurationSec}}",
      "- stylePreset: {{stylePreset}}",
      "- presetId: {{presetId}}",
      "- presetFormat: {{presetFormat}}",
      "- styleTags: {{styleTags}}",
      "- voiceMode: {{voiceMode}}",
      "- subtitleMode: {{subtitleMode}}",
      "- layoutMode: {{layoutMode}}",
      "- assetStrategy: {{assetStrategy}}",
      "- creativeBrief (author notes, beats, tone, must-include or avoid): {{creativeBrief}}",
      "",
      "Output rules:",
      "- Do not include markdown.",
      "- Do not include explanation.",
      "- Output JSON only.",
    ].join("\n"),
  },
  metadata: {
    stepKey: "metadata",
    version: "v1-file-registry",
    systemPrompt: [
      "You are a short-form video metadata writer for an AI video pipeline.",
      "",
      "Your job is to generate clean, searchable, platform-ready metadata for a short-form video.",
      "",
      "You must follow these rules:",
      "- Return valid JSON only.",
      "- Do not include markdown, code fences, commentary, or explanations.",
      "- Metadata must feel human, concise, and publishable.",
      "- Optimize for clarity, relevance, and searchability without spammy SEO tactics.",
      "- Avoid sensational, misleading, exaggerated, or repetitive wording.",
      "- Match all viewer-facing text to the requested target language.",
      "- Assume the video is published in a vertical 9:16 short-form format.",
      "",
      "The JSON schema must be:",
      "{",
      '  "title": string,',
      '  "description": string,',
      '  "tags": string[]',
      "}",
    ].join("\n"),
    userPrompt: [
      "Generate metadata for a short-form video.",
      "",
      'Return JSON with keys: "title", "description", "tags".',
      "",
      "Goals:",
      "- Create metadata that is searchable, clear, and natural for a short-form video platform.",
      "- Align the tone with the video idea and stylePreset.",
      "",
      "Constraints:",
      "- title should be concise, specific, and click-worthy without sensational claims.",
      "- title should usually stay within 40 to 70 characters unless the language naturally requires otherwise.",
      "- title should reflect the actual video content, not generic trendbait.",
      "- description should be 2 to 3 short sentences with clear context.",
      "- description should explain what the viewer will get, in natural language.",
      "- description should not repeat the title word-for-word.",
      "- tags should be a focused array of lower-case keywords.",
      "- tags should be relevant, non-redundant, and not overly broad.",
      "- Prefer 5 to 10 tags.",
      "- Do not include hashtags with # unless they are explicitly required by the platform.",
      "- Avoid duplicate tags, vague filler tags, or misleading keywords.",
      "",
      "Inputs:",
      "- videoTitle: {{videoTitle}}",
      "- targetLanguage: {{targetLanguage}}",
      "- stylePreset: {{stylePreset}}",
      "",
      "Output rules:",
      "- Do not include markdown.",
      "- Do not include explanation.",
      "- Output JSON only.",
    ].join("\n"),
  },
  "youtube-publish-metadata": {
    stepKey: "youtube-publish-metadata",
    version: "v1-youtube-publish-metadata",
    systemPrompt: [
      "You are a YouTube upload metadata assistant for an AI short-form video pipeline.",
      "",
      "You must follow these rules:",
      "- Return valid JSON only (one object).",
      "- Do not include markdown, code fences, commentary, or explanations.",
      "- Respect YouTube limits: title should stay within 100 characters when possible (hard max 500); description max 5000 characters; at most 30 tags; each tag non-empty.",
      "- youtubePublishDefaultLanguage must be a BCP-47 language tag such as ko, en, en-US (lowercase language, optional region).",
      "- youtubePublishCategoryId must be an integer from 1 to 99 when present (YouTube numeric category id).",
      "- Viewer-facing title, description, and tags should match the requested output locale when outputLocaleHint is provided.",
      "",
      "The JSON object may include only these optional keys (omit keys you cannot infer):",
      '- "youtubePublishTitle": string',
      '- "youtubePublishDescription": string',
      '- "youtubePublishTags": string[]',
      '- "youtubePublishCategoryId": number',
      '- "youtubePublishDefaultLanguage": string',
      "",
      "Do not include any other keys.",
    ].join("\n"),
    userPrompt: [
      "Propose YouTube upload metadata from the pipeline context below.",
      "",
      "Goals:",
      "- Align with the video story, hook, and narration from the scene outline.",
      "- Use channel defaults (tags, language, category, upload format) as a baseline; improve or specialize for this video when appropriate.",
      "- If existingJobYoutubeFieldsJson is non-empty, treat it as the editor's current draft and refine or complete it rather than discarding it.",
      "",
      "outputLocaleHint (preferred language for viewer-facing strings): {{outputLocaleHint}}",
      "",
      "jobBriefJson:",
      "{{jobBriefJson}}",
      "",
      "sceneOutlineJson (videoTitle, language, per-scene narration and subtitles):",
      "{{sceneOutlineJson}}",
      "",
      "channelDefaultsJson:",
      "{{channelDefaultsJson}}",
      "",
      "jobMetaHintsJson (videoTitle and any existing youtubePublish* on the job row):",
      "{{jobMetaHintsJson}}",
      "",
      "Output rules:",
      "- JSON object only.",
      "- Include at least one of the youtubePublish* fields with useful content.",
    ].join("\n"),
  },
};

export const loadDefaultLlmStepConfig = (
  stepKey: LlmStepKey,
): LlmStepConfig => {
  return defaultStepConfigs[stepKey];
};

export const loadDefaultLlmPromptTemplate = (
  stepKey: LlmStepKey,
): LlmPromptTemplate => {
  return defaultPromptTemplates[stepKey];
};

export const loadDefaultLlmStepSettings = (
  stepKey: LlmStepKey,
): LlmStepSettings => {
  return {
    config: loadDefaultLlmStepConfig(stepKey),
    promptTemplate: loadDefaultLlmPromptTemplate(stepKey),
    updatedAt: "1970-01-01T00:00:00.000Z",
    updatedBy: "system-default",
  };
};
